<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-custom">
            <div class="panel-heading">
                <a id="logo" href="<?php echo BASE; ?>">
                    <img class="img-responsive" src="<?php echo IMG; ?>hxphp-logo.png" alt="">
                </a>
            </div>
            <div class="panel-body">
                <div class="alert alert-block alert-danger">
                    <h4>Ops! Nada encontrado!</h4>
                    Desculpe-nos, mas a url solicitada não foi encontrada, cheque novamente, caso esteja correta, avise o administrador.
                </div>
            </div>
        </div>
    </div>
</div>
