<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-custom">
            <div class="panel-heading">
                <a id="logo" href="<?php echo BASE; ?>">
                    <img class="img-responsive" src="<?php echo IMG; ?>hxphp-logo.png" alt="">
                </a>
            </div>
            <div class="panel-body">
                <h4 class="alert alert-success">
                    Uhull! Agora você pode usar subpastas!
                </h4>
                <p>
                    As aplicações são as mais diversas possíveis e isso lhe ajudará, ainda mais, com a organização do projeto. Essa implementação permitirá uma fácil integração de back e front-end.
                </p>
                <p>
                    Por exemplo: Se estiver desenvolvendo um site com administrativo, poderá colocar todo o back-end nas subpastas <code>app/controllers/admin/</code> e <code>app/views/admin/</code> ao invés de duplicar o HXPHP para ambas as pastas.
                </p>
            </div>
        </div>
    </div>
</div>
